name: Deploy to PROD Environment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to PROD env with Serverless Framework
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set Environment Variables
        run: |
          echo "SECURITY_KEY=${{ secrets.SECURITY_KEY }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with SLS
        run: |
          export STAGE=prod
          export REGION=us-east-1
          npm run deploy
